name: node
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
services:
  tinyproxy:
    container_name: tinyproxy
    image: registry.gitlab.com/kalaksi-containers/tinyproxy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16m
    networks:
      main:
        ipv4_address: 10.5.0.13
    ports:
      - 8013:8888
    volumes:
      - ${BASE_DIR}/config/tinyproxy/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:ro
    profiles:
      - tinyproxy
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    deploy:
      resources:
        limits:
          memory: 128m
    networks:
      main:
        ipv4_address: 10.5.0.12
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    depends_on:
      - nginx
    profiles:
      - cloudflared
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32m
    networks:
      main:
        ipv4_address: 10.5.0.11
    volumes:
      - ${BASE_DIR}/config/nginx/templates/:/etc/nginx/templates/:ro
    environment:
      - TINYAUTH_DOMAIN=${TINYAUTH_DOMAIN}
      - BACKREST_DOMAIN=${BACKREST_DOMAIN}
      - DUFS_DOMAIN=${DUFS_DOMAIN}
  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16m
    networks:
      main:
        ipv4_address: 10.5.0.101
    environment:
      - DISABLE_CONTINUE=true
      - COOKIE_SECURE=true
      - APP_URL=https://${TINYAUTH_DOMAIN}
      - SECRET=${TINYAUTH_SECRET}
      - USERS=${TINYAUTH_USERS}
  backrest:
    container_name: backrest
    image: garethgeorge/backrest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    networks:
      main:
        ipv4_address: 10.5.0.102
    volumes:
      - ${BASE_DIR}/config/backrest:/config:ro
      - ${BASE_DIR}/data/backrest/data:/data
      - ${BASE_DIR}/data/backrest/cache:/cache
      - ${BASE_DIR}/data/backrest/repos:/repos
      - ${BASE_DIR}/data:/userdata
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
    profiles:
      - backrest
  dufs:
    container_name: dufs
    image: sigoden/dufs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    networks:
      main:
        ipv4_address: 10.5.0.103
    volumes:
      - ${BASE_DIR}/config/dufs:/config:ro
      - ${BASE_DIR}/data/dufs:/data
      - ${BASE_DIR}/data/aria2/data:/data/downloads
    environment:
      - DUFS_CONFIG=/config/config.yaml
      - DUFS_SERVE_PATH=/data
    profiles:
      - dufs
  aria2:
    container_name: aria2
    image: hurlenko/aria2-ariang
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    networks:
      main:
        ipv4_address: 10.5.0.104
    environment:
      - ARIA2RPCPORT=443
    volumes:
      - ${BASE_DIR}/config/aria2:/aria2/conf:ro
      - ${BASE_DIR}/data/aria2/data:/aria2/data
      - ${BASE_DIR}/data/aria2/session:/aria2/session
    profiles:
      - aria2
