name: node
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128m
    volumes:
      - ./nginx/templates/:/etc/nginx/templates/:ro
    environment:
      - TINYAUTH_DOMAIN=${TINYAUTH_DOMAIN}
      - BACKREST_DOMAIN=${BACKREST_DOMAIN}
    depends_on:
      - tinyauth
      - backrest
  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16m
    environment:
      - DISABLE_CONTINUE=true
      - COOKIE_SECURE=true
      - APP_URL=https://${TINYAUTH_DOMAIN}
      - SECRET=${TINYAUTH_SECRET}
      - USERS=${TINYAUTH_USERS}
  backrest:
    container_name: backrest
    image: garethgeorge/backrest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - ./backrest/repos:/repos
      - .:/userdata
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    profiles:
      - cloudflared
