name: node
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
services:
  tinyproxy:
    container_name: tinyproxy
    image: registry.gitlab.com/kalaksi-containers/tinyproxy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16m
    networks:
      main:
        ipv4_address: 10.5.0.13
    ports:
      - 8013:8888
    volumes:
      - ./config/tinyproxy/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:ro
    extra_hosts:
      - ${BACKREST_DOMAIN}:10.5.0.11
      - ${DUFS_DOMAIN}:10.5.0.11
      - ${ARIA2_DOMAIN}:10.5.0.11
      - ${LLDAP_DOMAIN}:10.5.0.11
      - ${AUTHELIA_DOMAIN}:10.5.0.11
      - ${VIKUNJA_DOMAIN}:10.5.0.11
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    deploy:
      resources:
        limits:
          memory: 128m
    networks:
      main:
        ipv4_address: 10.5.0.12
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    profiles: ["cloudflared", "${ENABLE_CLOUDFLARED:+enable}"]
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32m
    networks:
      main:
        ipv4_address: 10.5.0.11
    volumes:
      - ./config/nginx/templates/:/etc/nginx/templates/:ro
      - ./config/nginx/cert/:/etc/nginx/ssl/:ro
    environment:
      - BACKREST_DOMAIN=${BACKREST_DOMAIN}
      - DUFS_DOMAIN=${DUFS_DOMAIN}
      - ARIA2_DOMAIN=${ARIA2_DOMAIN}
      - LLDAP_DOMAIN=${LLDAP_DOMAIN}
      - AUTHELIA_DOMAIN=${AUTHELIA_DOMAIN}
      - VIKUNJA_DOMAIN=${VIKUNJA_DOMAIN}
    extra_hosts:
      - backrest:10.5.0.102
      - dufs:10.5.0.103
      - aria2:10.5.0.104
      - lldap:10.5.0.105
      - authelia:10.5.0.106
      - vikunja:10.5.0.107
    profiles: ["nginx", "${ENABLE_NGINX:+enable}"]
  backrest:
    container_name: backrest
    image: garethgeorge/backrest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    networks:
      main:
        ipv4_address: 10.5.0.102
    volumes:
      - ./config/backrest:/config:ro
      - ./data/backrest/data:/data
      - ./data/backrest/cache:/cache
      - ./data/backrest/repos:/repos
      - ./data:/userdata
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
    profiles: ["backrest", "${ENABLE_BACKREST:+enable}"]
  dufs:
    container_name: dufs
    image: sigoden/dufs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    networks:
      main:
        ipv4_address: 10.5.0.103
    volumes:
      - ./config/dufs:/config:ro
      - ./data/dufs:/data
      - ./data/aria2/data:/data/downloads
    environment:
      - DUFS_CONFIG=/config/config.yaml
      - DUFS_SERVE_PATH=/data
    profiles: ["dufs", "${ENABLE_DUFS:+enable}"]
  aria2:
    container_name: aria2
    image: hurlenko/aria2-ariang
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    networks:
      main:
        ipv4_address: 10.5.0.104
    environment:
      - ARIA2RPCPORT=443
    volumes:
      - ./config/aria2:/aria2/conf:ro
      - ./data/aria2/data:/aria2/data
      - ./data/aria2/session:/aria2/session
    profiles: ["aria2", "${ENABLE_ARIA2:+enable}"]
  lldap:
    container_name: lldap
    image: lldap/lldap:stable
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32m
    networks:
      main:
        ipv4_address: 10.5.0.105
    environment:
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS}
    volumes:
      - ./data/lldap:/data
      - ./config/lldap/lldap_config.toml:/data/lldap_config.toml
    profiles: ["lldap", "${ENABLE_LLDAP:+enable}"]
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 40m
    networks:
      main:
        ipv4_address: 10.5.0.106
    extra_hosts:
      - lldap:10.5.0.105
    environment:
      - X_AUTHELIA_CONFIG_FILTERS=template
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=${AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET=${AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET}
      - USER_DOMAIN=${AUTHELIA_DOMAIN}
      - USER_SESSION_DOMAIN=${AUTHELIA_SESSION_DOMAIN}
      - USER_LDAP_PASSWORD=${LLDAP_LDAP_USER_PASS}
      - VIKUNJA_DOMAIN=${VIKUNJA_DOMAIN}
      - VIKUNJA_CLIENTID=${VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTID}
      - VIKUNJA_CLIENTSECRET=${VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTSECRET}
      - BACKREST_DOMAIN=${BACKREST_DOMAIN}
    volumes:
      - ./config/authelia:/config
      - ./data/authelia:/data
    profiles: ["authelia", "${ENABLE_AUTHELIA:+enable}"]
  vikunja:
    container_name: vikunja
    image: vikunja/vikunja:unstable
    user: "0:0"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32m
    networks:
      main:
        ipv4_address: 10.5.0.107
    extra_hosts:
      - ${AUTHELIA_DOMAIN}:10.5.0.11
    environment:
      - VIKUNJA_SERVICE_JWTSECRET=${VIKUNJA_SERVICE_JWTSECRET}
      - VIKUNJA_SERVICE_PUBLICURL=https://${VIKUNJA_DOMAIN}
      - VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_AUTHURL=https://${AUTHELIA_DOMAIN}
      - VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTID=${VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTID}
      - VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTSECRET=${VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTSECRET}
    volumes:
      - ./config/nginx/cert/server.crt:/etc/ssl/certs/nginx.crt:ro
      - ./config/vikunja:/etc/vikunja:ro
      - ./data/vikunja/files:/app/vikunja/files
      - ./data/vikunja/db:/db
    profiles: ["vikunja", "${ENABLE_VIKUNJA:+enable}"]
