name: node
services:
  nginx:
    container_name: nginx
    image: nginx 
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128m
    volumes:
      - ./nginx/templates/:/etc/nginx/templates/:ro
